// Copyright (C) 2014 by wubenqi
// Distributable under the terms of either the Apache License (Version 2.0) or 
// the GNU Lesser General Public License, as specified in the COPYING file.
//
// By: wubenqi<wubenqi@gmail.com>
//

#ifndef PROTO_CONST_MESSAG_PDU_TYPES_H_
#define PROTO_CONST_MESSAG_PDU_TYPES_H_

#include "base/basictypes.h"

//////////////////////////////////////////////////////////////////////////
// module id
enum {
  SID_LOGIN = 0x0001,			// for login
  SID_BUDDY_LIST = 0x0002,		// for friend list
  SID_MSG = 0x0003,			//
  SID_SWITCH_SERVICE = 0x0004, //
  SID_GROUP = 0x0005,			// for group message
  SID_FILE = 0x0006, 			//
  SID_OTHER = 0x0007,		//
};

//////////////////////////////////////////////////////////////////////////
#define IM_PDU_TYPE_HEARTBEAT						1

//////////////////////////////////////////////////////////////////////////
// DB storage server related
#define IM_PDU_TYPE_STOP_RECEIVE_PACKET			100  // business server stop service
#define IM_PDU_TYPE_VALIDATE_REQUEST			110
#define IM_PDU_TYPE_VALIDATE_RESPONSE			111
#define IM_PDU_TYPE_FRIEND_LIST_REQUEST			122
#define IM_PDU_TYPE_FRIEND_LIST_RESPONSE		123
#define IM_PDU_TYPE_REMOVE_SESSION_REQUEST		124
#define IM_PDU_TYPE_REMOVE_SESSION_RESPONSE		125
#define IM_PDU_TYPE_DEPARTMENT_REQUEST          126
#define IM_PDU_TYPE_DEPARTMENT_RESPONSE         127

#define IM_PDU_TYPE_USERS_INFO_REQUEST			130
#define IM_PDU_TYPE_USERS_INFO_RESPONSE			131
#define IM_PDU_TYPE_ALL_USER_REQUEST			132	// 内部所有员工信息请求
#define IM_PDU_TYPE_ALL_USER_RESPONSE			133	//

#define IM_PDU_TYPE_MSG_DATA					140
#define IM_PDU_TYPE_UNREAD_MSG_COUNT_REQUEST	141
#define IM_PDU_TYPE_UNREAD_MSG_COUNT_RESPONSE	142
#define IM_PDU_TYPE_UNREAD_MSG_REQUEST			143
#define IM_PDU_TYPE_HISTORY_MSG_REQUEST			144
#define IM_PDU_TYPE_MSG_LIST_RESPONSE			145
#define IM_PDU_TYPE_MSG_READ_ACK				146
#define IM_PDU_TYPE_DB_QUERY_REQUEST			170
#define IM_PDU_TYPE_DB_QUERY_RESPONSE			171
#define IM_PDU_TYPE_DB_WRITE_RESPONSE			180
#define IM_PDU_TYPE_USER_ACTION_LOG				190

//////////////////////////////////////////////////////////////////////////
// pdu with business server
#define IM_PDU_TYPE_GROUP_LIST_REQUEST				300
#define IM_PDU_TYPE_GROUP_LIST_RESPONSE				301
#define IM_PDU_TYPE_GROUP_USER_LIST_REQUEST			302
#define IM_PDU_TYPE_GROUP_USER_LIST_RESPONSE		303
#define IM_PDU_TYPE_GROUP_UNREAD_MSG_CNT_REQUEST	304
#define IM_PDU_TYPE_GROUP_UNREAD_MSG_CNT_RESPONSE	305
#define IM_PDU_TYPE_GROUP_UNREAD_MSG_REQUEST		306
#define IM_PDU_TYPE_GROUP_HISTORY_MSG_REQUEST		307
#define IM_PDU_TYPE_GROUP_MSG_LIST_RESPONSE			308
#define IM_PDU_TYPE_GROUP_MSG_READ_ACK				309
#define IM_PDU_TYPE_GROUP_CREATE_TMP_GROUP_REQUEST	310
#define IM_PDU_TYPE_GROUP_CREATE_TMP_GROUP_RESPONSE	311
#define IM_PDU_TYPE_GROUP_CHANGE_MEMBER_REQUEST		312	// for internal use
#define IM_PDU_TYPE_GROUP_CHANGE_MEMBER_RESPONSE	313 // for internal use
#define IM_PDU_TYPE_GROUP_DIALOG_LIST_REQUEST		314 // recent contact group(normal group & tmp group)
#define IM_PDU_TYPE_GROUP_DIALOG_LIST_RESPONSE		315

#define IM_PDU_TYPE_GROUP_CREATE_NORMAL_GROUP_NOTIFY    316
#define IM_PDU_TYPE_GROUP_CHANGE_MEMBER_NOTIFY          317

//////////////////////////////////////////////////////////////////////////
// to storage server
#define IM_PDU_TYPE_FILE_HAS_OFFLINE_REQ			561
#define IM_PDU_TYPE_FILE_HAS_OFFLINE_RES			562
#define IM_PDU_TYPE_FILE_ADD_OFFLINE_REQ			563
#define IM_PDU_TYPE_FILE_DEL_OFFLINE_REQ			564

//////////////////////////////////////////////////////////////////////////
// MessageType
// command_id 
// 
#define MAKE_INT32(low, high) ((uint32)(((uint16)(low)) << 16 | ((uint32)((uint16)(high)))))

//////////////////////////////////////////////////////////////////////////
const uint32 MESSAGE_HEARTBEAT = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_HEARTBEAT);

//////////////////////////////////////////////////////////////////////////
// DB storage server related
const uint32 MESSAGE_STOP_RECEIVE_PACKET = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_STOP_RECEIVE_PACKET);
const uint32 MESSAGE_VALIDATE_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_VALIDATE_REQUEST);
const uint32 MESSAGE_VALIDATE_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_VALIDATE_RESPONSE);
const uint32 MESSAGE_FRIEND_LIST_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_FRIEND_LIST_REQUEST);
const uint32 MESSAGE_FRIEND_LIST_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_FRIEND_LIST_RESPONSE);
const uint32 MESSAGE_REMOVE_SESSION_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_REMOVE_SESSION_REQUEST);
const uint32 MESSAGE_REMOVE_SESSION_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_REMOVE_SESSION_RESPONSE);
const uint32 MESSAGE_DEPARTMENT_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_DEPARTMENT_REQUEST);
const uint32 MESSAGE_DEPARTMENT_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_DEPARTMENT_RESPONSE);
const uint32 MESSAGE_USERS_INFO_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_USERS_INFO_REQUEST);
const uint32 MESSAGE_USERS_INFO_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_USERS_INFO_RESPONSE);
const uint32 MESSAGE_ALL_USER_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_ALL_USER_REQUEST);
const uint32 MESSAGE_ALL_USER_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_ALL_USER_RESPONSE);
const uint32 MESSAGE_MSG_DATA = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_MSG_DATA);
const uint32 MESSAGE_UNREAD_MSG_COUNT_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_UNREAD_MSG_COUNT_REQUEST);
const uint32 MESSAGE_UNREAD_MSG_COUNT_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_UNREAD_MSG_COUNT_RESPONSE);
const uint32 MESSAGE_UNREAD_MSG_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_UNREAD_MSG_REQUEST);
const uint32 MESSAGE_HISTORY_MSG_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_HISTORY_MSG_REQUEST);
const uint32 MESSAGE_MSG_LIST_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_MSG_LIST_RESPONSE);
const uint32 MESSAGE_MSG_READ_ACK = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_MSG_READ_ACK);
const uint32 MESSAGE_DB_QUERY_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_DB_QUERY_REQUEST);
const uint32 MESSAGE_DB_QUERY_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_DB_QUERY_RESPONSE);
const uint32 MESSAGE_DB_WRITE_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_DB_WRITE_RESPONSE);
const uint32 MESSAGE_USER_ACTION_LOG = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_USER_ACTION_LOG);

//////////////////////////////////////////////////////////////////////////
// pdu with business server
const uint32 MESSAGE_GROUP_LIST_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_LIST_REQUEST);
const uint32 MESSAGE_GROUP_LIST_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_LIST_RESPONSE);
const uint32 MESSAGE_GROUP_USER_LIST_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_USER_LIST_REQUEST);
const uint32 MESSAGE_GROUP_USER_LIST_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_USER_LIST_RESPONSE);
const uint32 MESSAGE_GROUP_UNREAD_MSG_COUNT_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_UNREAD_MSG_CNT_REQUEST);
const uint32 MESSAGE_GROUP_UNREAD_MSG_COUNT_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_UNREAD_MSG_CNT_RESPONSE);
const uint32 MESSAGE_GROUP_UNREAD_MSG_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_UNREAD_MSG_REQUEST);
const uint32 MESSAGE_GROUP_HISTORY_MSG_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_HISTORY_MSG_REQUEST);
const uint32 MESSAGE_GROUP_MSG_LIST_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_MSG_LIST_RESPONSE);
const uint32 MESSAGE_GROUP_MSG_READ_ACK = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_MSG_READ_ACK);
const uint32 MESSAGE_GROUP_CREATE_TMP_GROUP_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_CREATE_TMP_GROUP_REQUEST);
const uint32 MESSAGE_GROUP_CREATE_TMP_GROUP_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_CREATE_TMP_GROUP_RESPONSE);
const uint32 MESSAGE_GROUP_CHANGE_MEMBER_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_CHANGE_MEMBER_REQUEST);
const uint32 MESSAGE_GROUP_CHANGE_MEMBER_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_CHANGE_MEMBER_RESPONSE);
const uint32 MESSAGE_GROUP_DIALOG_LIST_REQUEST = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_DIALOG_LIST_REQUEST);
const uint32 MESSAGE_GROUP_DIALOG_LIST_RESPONSE = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_DIALOG_LIST_RESPONSE);
const uint32 MESSAGE_GROUP_CREATE_NORMAL_GROUP_NOTIFY = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_CREATE_NORMAL_GROUP_NOTIFY);
const uint32 MESSAGE_GROUP_CHANGE_MEMBER_NOTIFY = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_GROUP_CHANGE_MEMBER_NOTIFY);

//////////////////////////////////////////////////////////////////////////
// to storage server
const uint32 MESSAGE_FILE_HAS_OFFLINE_REQ = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_FILE_HAS_OFFLINE_REQ);
const uint32 MESSAGE_FILE_HAS_OFFLINE_RES = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_FILE_HAS_OFFLINE_RES);
const uint32 MESSAGE_FILE_ADD_OFFLINE_REQ = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_FILE_ADD_OFFLINE_REQ);
const uint32 MESSAGE_FILE_DEL_OFFLINE_REQ = MAKE_INT32(SID_OTHER, IM_PDU_TYPE_FILE_DEL_OFFLINE_REQ);

#endif


